"""Sincronizando estado do banco de dados após stamp

Revision ID: 5d8045a1154d
Revises: d5f22ddb33de
Create Date: 2024-11-05 22:14:07.872336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8045a1154d'
down_revision = 'd5f22ddb33de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('codigo', sa.Float(), nullable=True),
    sa.Column('custo', sa.Float(), nullable=True),
    sa.Column('marca', sa.String(length=100), nullable=True),
    sa.Column('informacoes', sa.Text(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('data_inclusao', sa.String(length=100), nullable=True),
    sa.Column('data_validade', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produtos')
    # ### end Alembic commands ###
